//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dobachesky_Assn4_Console.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingInfo", Namespace="http://schemas.datacontract.org/2004/07/Dobachesky_Assn4")]
    [System.SerializableAttribute()]
    public partial class BillingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetNumberOfOrders", ReplyAction="http://tempuri.org/IOrderService/GetNumberOfOrdersResponse")]
        int GetNumberOfOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetNumberOfOrders", ReplyAction="http://tempuri.org/IOrderService/GetNumberOfOrdersResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetTotalCostForAnOrder", ReplyAction="http://tempuri.org/IOrderService/GetTotalCostForAnOrderResponse")]
        double GetTotalCostForAnOrder(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetTotalCostForAnOrder", ReplyAction="http://tempuri.org/IOrderService/GetTotalCostForAnOrderResponse")]
        System.Threading.Tasks.Task<double> GetTotalCostForAnOrderAsync(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetItemListForOrder", ReplyAction="http://tempuri.org/IOrderService/GetItemListForOrderResponse")]
        string GetItemListForOrder(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetItemListForOrder", ReplyAction="http://tempuri.org/IOrderService/GetItemListForOrderResponse")]
        System.Threading.Tasks.Task<string> GetItemListForOrderAsync(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/HowManyOrderedForAPartNo", ReplyAction="http://tempuri.org/IOrderService/HowManyOrderedForAPartNoResponse")]
        int HowManyOrderedForAPartNo(string sPartNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/HowManyOrderedForAPartNo", ReplyAction="http://tempuri.org/IOrderService/HowManyOrderedForAPartNoResponse")]
        System.Threading.Tasks.Task<int> HowManyOrderedForAPartNoAsync(string sPartNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetBillingAddressForAnOrder", ReplyAction="http://tempuri.org/IOrderService/GetBillingAddressForAnOrderResponse")]
        Dobachesky_Assn4_Console.OrderService.BillingInfo GetBillingAddressForAnOrder(int OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/GetBillingAddressForAnOrder", ReplyAction="http://tempuri.org/IOrderService/GetBillingAddressForAnOrderResponse")]
        System.Threading.Tasks.Task<Dobachesky_Assn4_Console.OrderService.BillingInfo> GetBillingAddressForAnOrderAsync(int OrderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : Dobachesky_Assn4_Console.OrderService.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<Dobachesky_Assn4_Console.OrderService.IOrderService>, Dobachesky_Assn4_Console.OrderService.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOfOrders() {
            return base.Channel.GetNumberOfOrders();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfOrdersAsync() {
            return base.Channel.GetNumberOfOrdersAsync();
        }
        
        public double GetTotalCostForAnOrder(int OrderID) {
            return base.Channel.GetTotalCostForAnOrder(OrderID);
        }
        
        public System.Threading.Tasks.Task<double> GetTotalCostForAnOrderAsync(int OrderID) {
            return base.Channel.GetTotalCostForAnOrderAsync(OrderID);
        }
        
        public string GetItemListForOrder(int OrderID) {
            return base.Channel.GetItemListForOrder(OrderID);
        }
        
        public System.Threading.Tasks.Task<string> GetItemListForOrderAsync(int OrderID) {
            return base.Channel.GetItemListForOrderAsync(OrderID);
        }
        
        public int HowManyOrderedForAPartNo(string sPartNo) {
            return base.Channel.HowManyOrderedForAPartNo(sPartNo);
        }
        
        public System.Threading.Tasks.Task<int> HowManyOrderedForAPartNoAsync(string sPartNo) {
            return base.Channel.HowManyOrderedForAPartNoAsync(sPartNo);
        }
        
        public Dobachesky_Assn4_Console.OrderService.BillingInfo GetBillingAddressForAnOrder(int OrderID) {
            return base.Channel.GetBillingAddressForAnOrder(OrderID);
        }
        
        public System.Threading.Tasks.Task<Dobachesky_Assn4_Console.OrderService.BillingInfo> GetBillingAddressForAnOrderAsync(int OrderID) {
            return base.Channel.GetBillingAddressForAnOrderAsync(OrderID);
        }
    }
}
